---
abstract: 'Parsing sequence informations in FASTA format.'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-FASTASequence
requires:
  Test::More: 0
  perl: 5.006001
resources:
  bugtracker: http://github.com/reneeb/Bio-FASTASequence/issues
  homepage: http://github.com/reneeb/Bio-FASTASequence
  repository: http://github.com/reneeb/Bio-FASTASequence.git
version: 0.07
